version: '3'
services:
  admin-service:
    build: .
    container_name: admin-server
    image: admin-service:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/e-learning
    ports:
      - 8080:8080
    network_mode: "host"
    restart: always
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=e-learning
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5000:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
  user-service:
    build: ../user-service/.
    container_name: user-service
    image: user-service:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/e-learning
    ports:
      - 8080:9999
    network_mode: "host"
    restart: always
    depends_on:
      - db

volumes:
  pgdata: